[ensemble]
    ne    = 40
    state = ['injrate', 'prodrate']

    prior_injrate  = [['mean', 'init_injrate.npz'], 
                      ['var', 22.5], 
                      ['limits', 0.0, 150.0]]

    prior_prodrate = [['mean', 'init_prodrate.npz'], 
                      ['var', 40.0], 
                      ['limits', 0.0, 200.0]]
    transform  = true
    num_models = 40

[optim]
    maxiter = 30
    tol     = 0.00001
    alpha   = 0.1
    beta    = 0.0
    alpha_maxiter = 5
    optimizer     = 'GA'
    restartsave   = true
    restart       = false
    hessian       = false
    nesterov      = false
    save_folder   = './results'

[fwdsim]
    npv_const = [['wop', 300],
                 ['wgp', 0],
                 ['wwp', 40],
                 ['wwi', 10],
                 ['disc', 0.1],
                 ['obj_scaling', -1E7]]
    parallel    = 40
    #simoptions	= ['mpi', 'mpirun -np 3']
    sim_flag    ='--min-time-step-before-shutting-problematic-wells-in-days=10 --time-step-after-event-in-days=10 --enable-well-operability-check=false --enable-tuning=true --tolerance-mb=1e-04'
    runfile     = 'EGG_MODEL'
    startdate   = '15/6/2011'
    reportpoint = 'report_dates.csv'
    reporttype  = 'dates' 
    datatype    = ['fopt', 'fgpt', 'fwpt', 'fwit']
